### ISSUE TITLE
Static IP's on Index.php

### ISSUE THREAD

**Issue by HermanRas** [Sheidbrink/GossipProtocol#1]
I updated the Static IP's on Index.php,  

but cant for the life of me get it up and working.. steps is used:

start x3 node sessions from command line "php ./node.php 5":
gossip5b57011305d60
gossip5b5701b537094
gossip5b5701ba7e8ba 

Open http://localhost/index.php
select the first node from the list, add UUID of the other x2 nodes with endpoints as below:
http://localhost/index.php?node=gossip5b5701b537094
http://localhost/index.php?node=gossip5b5701ba7e8ba 

when I click send the message on the node the data does not replicate? 
what am I doing wrong?

**Comment by Sheidbrink** [comment]
There are static IPs set in db.ph pand form.php as well did you change those?

**Comment by HermanRas** [comment]
Hi Sheidbrink yes, I updated them.

maybe just let me know how you would set the project up from scratch..   there is a very real possibility I'm just interpreting the Node / Peer setup wrong :-(..

in return, I will build up a nice README.MD for the project based on a total beginners perspective and contribute?

**Comment by Sheidbrink** [comment]
It looks like the problem is I was using an old jquery version and didnt include which version it was.
The way to set it up from scratch is to install mysql, php, and php-mysqli. you can then run different node.php for reading from the database and sending the messages the command is `php node.php <timeout> <node#>`, and then run index.php for the web interface. you just need to change the hardcoded ip addrs and then the db.php login info to the database.

If I get time I'll try and figure things out more, but this is old school code and as you can see poorly documented so I dont remember much.

**Comment by Sheidbrink** [comment]
Sorry that took so long. I pushed the changes. so you should be able to run this on localhost and with the sql database using 'root' and 'password' for the username and password. if you look at the last commit you can see the lines you need to change to run on a different ip or using a different username and password.

I tested it running:
Apache 2.4.29
php 7.2.7
mysql 14.14

**Comment by Sheidbrink** [comment]
Hopefully this has been resolved
